### ISSUE TITLE
Shift+Additional Key Broken On Linux

### ISSUE THREAD

**Issue by thatzopoulos** [thebracket/bracket-lib#66]
rltk_rs on my Linux machine can log that shift is being pressed but is unable to tell that any other keys are being pressed after it. I have tested the code on a Mac, Windows, and Archlinux machine and can confirm that the code only has problems on Linux. I have not figured out the source of this issue yet but will update this issue with a solution if I do.

**Comment by spenserblack** [comment]
I've found this while running the keyboard example

- `alt` -> `shift` -> letter
`ctx.key` matches `Some(key)` 3 times
- `shift` -> letter
2 matches to `Some(key)`
- `shift` -> numeric (excluding 2)
1 match, on `shift` being pressed. Strangely, `2` seems to be the only numeric key that will match when `shift` is held :thinking: 
- `shift` -> `alt` ->  letter
2 matches to `Some`, on `shift` down and on letter down, but status of `alt` is correctly logged as `true`
- `shift` -> `ctrl` seems to work as intended

So the troublesome key combinations I found are `shift`+`alt` and `shift`+[any numeric except `2`]

**Comment by DrMelon** [comment]
Hello there. Since updating to 0.8.0, I've noticed that the `shift`, `control`, and `alt` variables of the `BTerm` context don't seem to be getting set anymore when the modifier keys are pressed. I thought this issue thread would be the best place to bring it up, even though I'm currently developing in a Windows environment.
